name: Event Classifier CI
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: make gradlew executable
        run: chmod +x gradlew
      - name: decode keystore
        run: echo "${{ secrets.SIGNING_KEY_BASE64 }}" | base64 --decode > keystore.jks
      - name: Debug keystore generated in CI
        run: |
          ls -lh keystore.jks
          file keystore.jks
          keytool -list -v -keystore keystore.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
      - name: set environment variables
        run: |
          echo "SIGNING_KEYSTORE=$PWD/keystore.jks" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
      - name: build release
        run: ./gradlew assembleRelease
      - name: upload to artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: app/build/outputs/apk/release/app-release.apk
